# Generated by Django 4.0.3 on 2022-04-03 09:03

from django.db import migrations, models
import university.models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_rename_famousuniversities_famousuniversitie'),
    ]

    operations = [
        migrations.AddField(
            model_name='famousuniversitie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=university.models.upload_location),
        ),
    ]
