# Generated by Django 4.0.3 on 2022-04-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_famousuniversitie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='famousuniversitie',
            name='about',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
